name: nabd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gap: ^1.0.0
  flutter_svg: ^2.2.4
  onbackground_shared_prefrences: ^0.0.2
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
